### ISSUE TITLE
SpecHUD / TankHUD kether revamp

### ISSUE THREAD

**Issue by Murzysko** [Krevik/Kether.pl-L4D2-Server#40]
I'd like to propose shorter text for Tank Report from:

[Tank Report] Tank was alive for a total time of: 03:08.
[Tank Report] Tank dealt a total of 172 damage with: 1 rocks, 2 punches, 1 object hits.

to:

[Tank Report] Time: 03:08 | Damage 172 with: 1 rocks, 2 punches, 1 object hits.

It will make 1 free line in the chat

**Comment by Krevik** [comment]
TODO:
-add support for multiple tank controls
-fix damage and hit count not being properly count when the hit results in incap
-To keep up the SOLID principles, move the logic to a new plugin and provide necessary forwards/natives:
 -create new plugin and move the logic code into there
 -fix aforementioned problems
 -move print info (using forward) to l4d2_tank_damage_announce OR instead of creating new plugin, implement the logic 
  here.

**Comment by crab-hash** [comment]
I found a problem, when I was playing tank vs. computer human, there was only survival time, no damage reporting, when I was playing against computer tank, the chat bar was able to report the damage and survival time correctly
